add chapter 'Returned widget' chapter
AaronErhardt/AaronErhardt.github.io pull request #59
Opened 2022-02-24 21:23 UTC by tronta

First draft of an additional chapter to describe the returned widget feature of the macro.

What do you think?
Probably an own example would be better…
Do you have an example for an optional widget? Did you implement that? I forgot.

2022-02-24 21:44 UTC, AaronErhardt commented
Thanks! Looks good.

Actually, there might not be any optional widgets anymore because gtk-rs decided to trust the nullability guarantees of C implementations. In other words, they will trust the C code that it catches null pointers and therefore the bindings can replace `Option<T>` with `T`. For us this means no optional returned widgets AFAIK. The syntax still exists and should be documented, but it will be enough to just leave a note, that `Option<Widget>` can be handled by `-> ? { ... }`

You can also see the change from the latest update of the libadwaita dependency: https://github.com/AaronErhardt/Relm4/commit/5674e1f5c0abc6afa4ea58b303dbae6db56bc90d#diff-f54b40e447a67dab371dd5913ec90fe6daac60a5558891c738a942f93461a1d0R94-R104

2022-02-25 07:04 UTC, tronta commented
Do you know, what's the difference between `set_label` and `set_title`?

2022-02-25 07:28 UTC, AaronErhardt requested changes
Just two small things

2022-02-25 07:28 UTC, AaronErhardt commented on src/widget_macro.md
> +Cases when an `Option<_>` is returned can be handled by the following:
I'd either write just `Option` or `Option<Widget>`, otherwise it looks like the inner type isn't used.

2022-02-25 07:28 UTC, AaronErhardt commented on src/widget_macro.md
> +    set_label: "Stopwatch",
Setting the label to "Stopwatch" doesn't make a lot of sense. Maybe something like "42 seconds have passed". After all, that's the content of your page.

2022-02-25 16:45 UTC, tronta commented
btw I stole the screenshot from the Adwaita Demo app, that's why I did not change it's content…

2022-02-25 17:28 UTC, AaronErhardt commented
Perfect, thanks again!

2022-02-25 17:28 UTC, merged